/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import conexion.Conexion;
import modelo.ComboItem;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import javax.swing.ImageIcon;
import javax.swing.Icon;

import java.awt.Image;
/**
 *
 * @author Cristopher GP
 */
public class VistaGeneros extends javax.swing.JPanel {

    /**
     * Creates new form VistaGeneros
     */
    public VistaGeneros(String rol) {
        initComponents();
         cargarGeneros();
    }
private void cargarGeneros(){

    try{

        Connection con = Conexion.conectar();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(
            "SELECT * FROM generos"
        );

        cbGenero.removeAllItems();

        while(rs.next()){

            cbGenero.addItem(

                new ComboItem(

                    rs.getInt("id_genero"),
                    rs.getString("nombre")
                )
            );
        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(this,
                "Error");
    }
}

private void cargarPeliculasGenero(){

    DefaultTableModel modelo =
            new DefaultTableModel();

    modelo.addColumn("Película");
    modelo.addColumn("Año");
    modelo.addColumn("Clasificación");
    modelo.addColumn("Duración");
    modelo.addColumn("Género");

    tablaPeliculasGenero.setModel(modelo);

    try{

        ComboItem genero =
                (ComboItem) cbGenero.getSelectedItem();

        Connection con = Conexion.conectar();

        PreparedStatement ps =
                con.prepareStatement(

            "SELECT * FROM vista_peliculas_generos " +
"WHERE id_genero=?"
        );

        ps.setInt(1, genero.getId());

        ResultSet rs = ps.executeQuery();

        while(rs.next()){

            Object[] fila = new Object[5];

            fila[0] = rs.getString("titulo");
            fila[1] = rs.getInt("anio");
            fila[2] = rs.getString("clasificacion");
            fila[3] = rs.getInt("duracion") + " min";
            fila[4] = rs.getString("genero");

            modelo.addRow(fila);
        }

    }catch(Exception e){

        JOptionPane.showMessageDialog(this,
                "Error");
    }
}
private void mostrarInfoGenero(){

    try{

        ComboItem genero =
                (ComboItem) cbGenero.getSelectedItem();

        Connection con = Conexion.conectar();

        PreparedStatement ps =
                con.prepareStatement(

            "SELECT COUNT(*) total " +

            "FROM peliculas " +

            "WHERE id_genero=?"
        );

        ps.setInt(1, genero.getId());

        ResultSet rs = ps.executeQuery();

        if(rs.next()){

            txtInfoGenero.setText(

                "Género: " +

                genero.toString() +

                "\n\nPelículas encontradas: " +

                rs.getInt("total")
            );
        }

    }catch(Exception e){

    }
}

private void mostrarPortada(String titulo){

    try{

        Connection con = Conexion.conectar();

        PreparedStatement ps =
                con.prepareStatement(

            "SELECT portada FROM peliculas " +
            "WHERE titulo=?"
        );

        ps.setString(1, titulo);

        ResultSet rs = ps.executeQuery();

        if(rs.next()){

            byte[] imagen =
                    rs.getBytes("portada");

            ImageIcon img =
                    new ImageIcon(imagen);

            Icon icono =
                    new ImageIcon(

                        img.getImage().getScaledInstance(

                            lblPortadaGenero.getWidth(),
                            lblPortadaGenero.getHeight(),

                            Image.SCALE_DEFAULT
                        )
                    );

            lblPortadaGenero.setIcon(icono);
        }

    }catch(Exception e){

    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtInfoGenero = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPeliculasGenero = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lblPortadaGenero = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setText("Generos de Peliculas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 200, 0));
        jLabel2.setText("Busqueda Generos:");

        cbGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGeneroActionPerformed(evt);
            }
        });

        txtInfoGenero.setColumns(20);
        txtInfoGenero.setRows(5);
        jScrollPane1.setViewportView(txtInfoGenero);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 200, 0));
        jLabel3.setText("Información Genero:");

        tablaPeliculasGenero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPeliculasGenero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeliculasGeneroMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPeliculasGenero);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 200, 0));
        jLabel4.setText("Peliculas del Genero:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 200, 0));
        jLabel6.setText("Portada Genero");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 481, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(lblPortadaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(86, 86, 86))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblPortadaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPeliculasGeneroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeliculasGeneroMouseClicked
        int fila =
            tablaPeliculasGenero.getSelectedRow();

    String titulo =
            tablaPeliculasGenero
            .getValueAt(fila, 0)
            .toString();

    mostrarPortada(titulo);
    }//GEN-LAST:event_tablaPeliculasGeneroMouseClicked

    private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGeneroActionPerformed
         cargarPeliculasGenero();

    mostrarInfoGenero();
    }//GEN-LAST:event_cbGeneroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<ComboItem> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPortadaGenero;
    private javax.swing.JTable tablaPeliculasGenero;
    private javax.swing.JTextArea txtInfoGenero;
    // End of variables declaration//GEN-END:variables
}
