/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import conexion.Conexion;
import modelo.ComboItem;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Cristopher GP
 */
public class VistaResenas extends javax.swing.JPanel {
int idSeleccionado = 0;

String rol;
String usuario;
String usuarioResena = "";
    /**
     * Creates new form VistaResenas
     */
    public VistaResenas(String rol, String usuario) {
        initComponents();
        
        this.rol = rol;
    this.usuario = usuario;
    

    cargarPeliculas();
    cargarTabla();
    calcularPromedio();
    configurarRoles();
    }

    private void cargarPeliculas(){

    try {

        Connection con = Conexion.conectar();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(
            "SELECT * FROM peliculas"
        );

        cbPelicula.removeAllItems();

        while(rs.next()){

            cbPelicula.addItem(
                new ComboItem(
                    rs.getInt("id_pelicula"),
                    rs.getString("titulo")
                )
            );
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error al cargar películas");
    }
}
    
    private void cargarTabla(){

    DefaultTableModel modelo = new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Película");
    modelo.addColumn("Usuario");
    modelo.addColumn("Calificación");
    modelo.addColumn("Comentario");
    modelo.addColumn("Fecha");

    tablaResenas.setModel(modelo);

    try {

        Connection con = Conexion.conectar();

        Statement st = con.createStatement();

        ResultSet rs = st.executeQuery(

            "SELECT * FROM vista_resenas"
        );

        while(rs.next()){

            Object[] fila = new Object[6];

            fila[0] = rs.getInt("id_resena");
            fila[1] = rs.getString("titulo");
            fila[2] = rs.getString("usuario");
            fila[3] = rs.getInt("calificacion");
            fila[4] = rs.getString("comentario");
            fila[5] = rs.getDate("fecha");

            modelo.addRow(fila);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error al cargar reseñas");
    }
}
    
    private void limpiar(){

    txtComentario.setText("");
    idSeleccionado = 0;
}
    
    private void configurarRoles(){

    if(rol.equals("consultor")){

        // Puede agregar
        btnAgregar.setEnabled(true);

        // Eliminar depende de la reseña seleccionada
        btnEliminar.setEnabled(false);

    } else {

        // admin y operador solo ven

        btnAgregar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }
}
    
    private void verificarPermisoEliminar(){

    if(rol.equals("consultor")){

        if(usuario.equals(usuarioResena)){

            btnEliminar.setEnabled(true);

        } else {

            btnEliminar.setEnabled(false);
        }
    }
}
    
    private void calcularPromedio(){

    try {

        ComboItem pelicula =
                (ComboItem) cbPelicula.getSelectedItem();

        Connection con = Conexion.conectar();

        PreparedStatement ps = con.prepareStatement(

            "SELECT AVG(calificacion) promedio " +
            "FROM resenas WHERE id_pelicula=?"
        );

        ps.setInt(1, pelicula.getId());

        ResultSet rs = ps.executeQuery();

        if(rs.next()){

            double promedio =
                    rs.getDouble("promedio");

            lblPromedio.setText(
                    "Promedio: " +
                    String.format("%.1f", promedio)
            );
        }

    } catch (Exception e) {

        lblPromedio.setText("Promedio: 0");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbPelicula = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaResenas = new javax.swing.JTable();
        cbCalificacion = new javax.swing.JComboBox<>();
        lblPromedio = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        cbPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeliculaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setText("Reseñas de Usuarios");

        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane1.setViewportView(txtComentario);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");

        btnLimpiar.setText("Limpiar");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 200, 0));
        jLabel2.setText("Pelicula:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 200, 0));
        jLabel3.setText("Calificación");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 200, 0));
        jLabel4.setText("Comentarios:");

        tablaResenas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaResenas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaResenasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaResenas);

        cbCalificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "⭐ 1", "⭐⭐ 2", "⭐⭐⭐ 3", "⭐⭐⭐⭐ 4", "⭐⭐⭐⭐⭐ 5" }));

        lblPromedio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPromedio.setForeground(new java.awt.Color(255, 200, 0));
        lblPromedio.setText("Promedio:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(cbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnAgregar)
                        .addGap(128, 128, 128)
                        .addComponent(btnEliminar)
                        .addGap(89, 89, 89)
                        .addComponent(btnLimpiar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cbCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblPromedio)))
                .addGap(0, 118, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCalificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPromedio))
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregar)
                    .addComponent(btnLimpiar))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       try {

        ComboItem pelicula =
                (ComboItem) cbPelicula.getSelectedItem();

        Connection con = Conexion.conectar();

        PreparedStatement ps = con.prepareStatement(

            "INSERT INTO resenas " +

            "(id_pelicula, usuario, calificacion, comentario, fecha) " +

            "VALUES (?,?,?,?,?)"
        );

        ps.setInt(1, pelicula.getId());

        ps.setString(2, usuario);

        ps.setInt(3,
    cbCalificacion.getSelectedIndex() + 1
        );

        ps.setString(4,
                txtComentario.getText()
        );

        java.sql.Date fechaActual =
                new java.sql.Date(
                        System.currentTimeMillis()
                );

        ps.setDate(5, fechaActual);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this,
                "Reseña agregada");

        limpiar();

        cargarTabla();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,
                "Error: " + e);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void tablaResenasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaResenasMouseClicked
        int fila = tablaResenas.getSelectedRow();

    idSeleccionado = Integer.parseInt(
            tablaResenas.getValueAt(fila, 0).toString()
    );

    usuarioResena =
            tablaResenas.getValueAt(fila, 2).toString();

    // comentario
    txtComentario.setText(
            tablaResenas.getValueAt(fila, 4).toString()
    );

    // calificación
    int calificacion =
            Integer.parseInt(
                    tablaResenas.getValueAt(fila, 3).toString()
            );

    cbCalificacion.setSelectedIndex(calificacion - 1);

    // película
    String peliculaTabla =
            tablaResenas.getValueAt(fila, 1).toString();

    for(int i = 0; i < cbPelicula.getItemCount(); i++){

        ComboItem item = cbPelicula.getItemAt(i);

        if(item.toString().equals(peliculaTabla)){

            cbPelicula.setSelectedIndex(i);

            break;
        }
    }

    // actualizar promedio
    calcularPromedio();

    verificarPermisoEliminar();
    }//GEN-LAST:event_tablaResenasMouseClicked

    private void cbPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeliculaActionPerformed
        calcularPromedio();
    }//GEN-LAST:event_cbPeliculaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbCalificacion;
    private javax.swing.JComboBox<ComboItem> cbPelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPromedio;
    private javax.swing.JTable tablaResenas;
    private javax.swing.JTextArea txtComentario;
    // End of variables declaration//GEN-END:variables
}
