/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.JFileChooser;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import conexion.Conexion;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.sql.ResultSet;
import modelo.ComboItem;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;
import java.awt.image.BufferedImage;
import javax.imageio.ImageIO;
/**
 *
 * @author Cristopher GP
 */
public class VistaPeliculas extends javax.swing.JPanel {
FileInputStream fis;
int longitudBytes;
int idSeleccionado;
TableRowSorter<DefaultTableModel> sorter;
    /**
     * Creates new form VistaPeliculas
     */
    public VistaPeliculas() {
        initComponents();
    }
String rol;

public VistaPeliculas(String rol) {
    initComponents();
     this.rol = rol;

    cargarGeneros();
    cargarDirectores();
    cargarTabla();

    configurarRoles();
}
private void configurarRoles() {

    if(rol.equals("consultor")){
        btnAgregar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }

    if(rol.equals("operador")){
        // puede todo aquí
    }
}
private void limpiar(){
    txtTitulo.setText("");
    txtAnio.setText("");
    txtDuracion.setText("");
    lblImagen.setIcon(null);

    fis = null;
    idSeleccionado = 0;
}
private void cargarTabla(){

    DefaultTableModel modelo =
            new DefaultTableModel();

    modelo.addColumn("ID");
    modelo.addColumn("Título");
    modelo.addColumn("Año");
    modelo.addColumn("Duración");
    modelo.addColumn("Género");
    modelo.addColumn("Director");

    tablaPeliculas.setModel(modelo);

    try {

        Connection con =
                Conexion.conectar();

        Statement st =
                con.createStatement();

        ResultSet rs =
                st.executeQuery(

            "SELECT * FROM vista_peliculas"
        );

        while(rs.next()){

            Object[] fila =
                    new Object[6];

            fila[0] =
                    rs.getInt("id_pelicula");

            fila[1] =
                    rs.getString("titulo");

            fila[2] =
                    rs.getInt("anio");

            fila[3] =
                    rs.getInt("duracion");

            fila[4] =
                    rs.getString("genero");

            fila[5] =
                    rs.getString("director");

            modelo.addRow(fila);
        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this,

                "Error al cargar tabla:\n"
                + e);
    }

    sorter =
        new TableRowSorter<>(
            (DefaultTableModel)
            tablaPeliculas.getModel()
        );

    tablaPeliculas.setRowSorter(sorter);
}
private void cargarGeneros(){

    try {
        Connection con = Conexion.conectar();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM generos");

        cbGenero.removeAllItems();

        while(rs.next()){
            cbGenero.addItem(new modelo.ComboItem(
                rs.getInt("id_genero"),
                rs.getString("nombre")
            ));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar géneros");
    }
}
private void cargarDirectores(){

    try {
        Connection con = Conexion.conectar();
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM directores");

        cbDirector.removeAllItems();

        while(rs.next()){
            cbDirector.addItem(new modelo.ComboItem(
                rs.getInt("id_director"),
                rs.getString("nombre")
            ));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error al cargar directores");
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        txtTitulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbDirector = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        txtDuracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbClasificacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        lblImagen = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnImagen = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 200, 0));
        jLabel1.setText("Registro de Peliculas");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 200, 0));
        jLabel2.setText("Título de la pelicula:");

        jLabel3.setForeground(new java.awt.Color(255, 200, 0));
        jLabel3.setText("Género:");

        cbDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDirectorActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 200, 0));
        jLabel4.setText("Director/a:");

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });

        txtDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDuracionActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 200, 0));
        jLabel5.setText("Año de estreno:");

        jLabel6.setForeground(new java.awt.Color(255, 200, 0));
        jLabel6.setText("Duración (min):");

        cbClasificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AA", "A", "B", "B15", "C", "D", " " }));

        jLabel7.setForeground(new java.awt.Color(255, 200, 0));
        jLabel7.setText("Clasificación");

        jLabel8.setForeground(new java.awt.Color(255, 200, 0));
        jLabel8.setText("Portada/cartel (BLOB)");

        btnLimpiar.setText("Limpiar");

        btnImagen.setText("Insertar Imagen");
        btnImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImagenActionPerformed(evt);
            }
        });

        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeliculasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaPeliculas);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 200, 0));
        jLabel9.setText("Buscar Pelicula");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImagen)
                .addGap(146, 146, 146))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar)
                        .addGap(79, 79, 79)
                        .addComponent(btnEditar)
                        .addGap(77, 77, 77)
                        .addComponent(btnLimpiar)
                        .addGap(49, 49, 49))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnio)
                            .addComponent(cbClasificacion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(85, 85, 85)
                        .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(0, 194, Short.MAX_VALUE))
                                    .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtDuracion))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(cbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addGap(141, 141, 141))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImagen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if(idSeleccionado == 0){
        JOptionPane.showMessageDialog(this, "Selecciona un registro");
        return;
    }

    try {
        Connection con = Conexion.conectar();

        PreparedStatement ps = con.prepareStatement(
            "UPDATE peliculas SET titulo=?, anio=?, duracion=? WHERE id_pelicula=?"
        );

        ps.setString(1, txtTitulo.getText());
        ps.setInt(2, Integer.parseInt(txtAnio.getText()));
        ps.setInt(3, Integer.parseInt(txtDuracion.getText()));
        ps.setInt(4, idSeleccionado);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Actualizado correctamente");

        limpiar();
        cargarTabla();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void cbDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbDirectorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // 🔹 VALIDACIÓN BÁSICA
    if(txtTitulo.getText().isEmpty() || txtAnio.getText().isEmpty() || txtDuracion.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Llena todos los campos");
        return;
    }

    if(fis == null){
        JOptionPane.showMessageDialog(this, "Selecciona una imagen");
        return;
    }

    try {
        Connection con = Conexion.conectar();

        PreparedStatement ps = con.prepareStatement(
            "INSERT INTO peliculas (titulo,id_genero,id_director,anio,duracion,clasificacion,portada) VALUES (?,?,?,?,?,?,?)"
        );

        ps.setString(1, txtTitulo.getText());
        
        modelo.ComboItem genero = (modelo.ComboItem) cbGenero.getSelectedItem();
modelo.ComboItem director = (modelo.ComboItem) cbDirector.getSelectedItem();

ps.setInt(2, genero.getId());
ps.setInt(3, director.getId());;

        ps.setInt(4, Integer.parseInt(txtAnio.getText()));
        ps.setInt(5, Integer.parseInt(txtDuracion.getText()));
        ps.setString(6, cbClasificacion.getSelectedItem().toString());
        ps.setBinaryStream(7, fis, longitudBytes);

        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Película guardada correctamente");

        limpiar();
        cargarTabla();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e);
    }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImagenActionPerformed

        try {

    JFileChooser file =
            new JFileChooser();

    int opcion =
            file.showOpenDialog(this);

    if(opcion == JFileChooser.APPROVE_OPTION){

        File archivo =
                file.getSelectedFile();

        BufferedImage bufferedImage =
        ImageIO.read(archivo);

if(bufferedImage == null){

    JOptionPane.showMessageDialog(this,

        "Formato de imagen no compatible.\n" +

        "Use JPG o PNG reales."
    );

    return;
}

        Image imgEscalada =
                bufferedImage.getScaledInstance(

                    lblImagen.getWidth(),
                    lblImagen.getHeight(),

                    Image.SCALE_SMOOTH
                );

        lblImagen.setIcon(

            new ImageIcon(imgEscalada)
        );

        fis = new FileInputStream(archivo);

        longitudBytes =
                (int) archivo.length();
    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(this,

            "Error al cargar imagen: "
            + e);
}
    }//GEN-LAST:event_btnImagenActionPerformed

    private void tablaPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeliculasMouseClicked
        int fila = tablaPeliculas.getSelectedRow();

    if(fila >= 0){
        idSeleccionado = Integer.parseInt(tablaPeliculas.getValueAt(fila, 0).toString());

        txtTitulo.setText(tablaPeliculas.getValueAt(fila, 1).toString());
        txtAnio.setText(tablaPeliculas.getValueAt(fila, 2).toString());
        txtDuracion.setText(tablaPeliculas.getValueAt(fila, 3).toString());

        // 🔥 TRAER IMAGEN DESDE BD
        try {
            Connection con = Conexion.conectar();

            PreparedStatement ps = con.prepareStatement(
                "SELECT portada FROM peliculas WHERE id_pelicula=?"
            );

            ps.setInt(1, idSeleccionado);

            ResultSet rs = ps.executeQuery();

            if(rs.next()){
                byte[] imagenBytes = rs.getBytes("portada");

                if(imagenBytes != null){
                    Image img = new ImageIcon(imagenBytes).getImage();
                    Image imgEscalada = img.getScaledInstance(
                            lblImagen.getWidth(),
                            lblImagen.getHeight(),
                            Image.SCALE_SMOOTH
                    );

                    lblImagen.setIcon(new ImageIcon(imgEscalada));
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al mostrar imagen");
        }
    }
    }//GEN-LAST:event_tablaPeliculasMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(idSeleccionado == 0){
        JOptionPane.showMessageDialog(this, "Selecciona un registro");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas eliminar?");

    if(confirm == 0){
        try {
            Connection con = Conexion.conectar();

            PreparedStatement ps = con.prepareStatement(
                "DELETE FROM peliculas WHERE id_pelicula=?"
            );

            ps.setInt(1, idSeleccionado);
            ps.executeUpdate();

            JOptionPane.showMessageDialog(this, "Eliminado");

            limpiar();
            cargarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDuracionActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String texto = txtBuscar.getText();

    if(texto.trim().length() == 0){
        sorter.setRowFilter(null);
    } else {
        sorter.setRowFilter(RowFilter.regexFilter("(?i)" + texto));
    }
    }//GEN-LAST:event_txtBuscarKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnImagen;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cbClasificacion;
    private javax.swing.JComboBox<ComboItem> cbDirector;
    private javax.swing.JComboBox<ComboItem> cbGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JTable tablaPeliculas;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDuracion;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
